### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by k1tzu** [RoCat/winston-journald#7]
```const winston = require('winston');
require('winston-journald').Journald;
winston.setLevels(winston.config.syslog.levels);

const logger = new (winston.Logger)({
    transports: [
        new (winston.transports.Console)({
            }),
        new (winston.transports.Journald)({
        })
    ],exitOnError:false

});

logger.error("HELLO WORLD!");
```
I see message in the console, but I see nothing in the journald.
Arch Linux 3.14.79+ aarch64

**Comment by RoCat** [comment]
Hello,
Tryed the exact same code (just adding `var winston = require('winston')` at the top, I assume you did it too)

works on my configuration:
nodejs: 6.10.0
ubuntu 16.04
kernel 4.4.0-72-generic
systemd 229

**Comment by k1tzu** [comment]
I've ended up with a working solution:
```
const Journald = require( 'systemd-journald' );
const logger = new Journald( { syslog_identifier: "myprog" } );
logger.error("HELLO WORLD!");
```
Who knows what was wrong with that one - maybe 3.x kernel or older systemd. I saw no debug/error messages from winston also.
